### ISSUE TITLE
Cannot always add outputs

### ISSUE THREAD

**Issue by mcusgithub** [ZhangGe6/onnx-modifier#75]
Same as #57 (reopening)
Same issue as before (tested with YOLOv8n this time), and the initial workaround does not work anymore unfortunately.
For instance: 1) delete final "concat" op, 2) create one "output" for each concat (now deleted) input (2 total), 3) save, 4) reload = outputs are missing (and/or have the wrong shape depending on some unknown condition)

**Comment by mcusgithub** [comment]
New workaround (not sure if all save/reload steps are required): Add "shape" operator, save with size inference, reload, Add "output", save again, reload, delete "shape" operator, save again.

**Comment by ZhangGe6** [comment]
@mcusgithub Thanks for reporting. The issue of "adding output" is really our old friend. It is usually caused by unperfect auto shape inference. I have tried to fix it by using [onnx-tool](https://github.com/ThanatosShinji/onnx-tool) for shape inference. With the latest code, both the editing of  YOLOv8n and the squeezenet in #57 work as expected.

![issue75](https://github.com/ZhangGe6/onnx-modifier/assets/63796752/6e580114-95d8-477e-ac81-a26df4fe3241)
